/*
¬°¤*,¸¸,*¤°¬¯¬°¤*,¸_¸,*¤°¬°¤*,¸,*¤°¬¯¬°¤*,¸_¸,*¤°¬°¤*,¸,*¤°¬¯¬°¤*,¸_¸,*¤°¬°¤*,¸
¸,*¤°¬¯¬°¤*,¸_¸,*¤°¬°¤*,¸,*¤°¬¯¬°¤*,¸_¸,*¤°¬°¤*,¸,*¤°¬¯¬°¤*,¸_¸,*¤°¬°¤*,¸,*¤°¬¯

  __/¯\____ ___/\__   _/\__   _/\_   _/\__   _/\___ ___/\__   __/\_   _/\__   
  \_  ____/_> ____ \_/  _  \_ \  <  /_    \_/     _>> ____ \_ >    \_/  _  \_ 
  _> ___/ ¯>__> <<__// __  _/ |>  ></ _/>  </  ¯  \\__> <<__//  /\  // __  _/ 
 _>  \7   <__/:. \__/:. \>  \_/   L/  _____/.  7> .\_/:. \__/  <_/ </:. \>  \_ 
|:::::::::::::::::::::::/:::::::::::::>::::::::/::::::::::::::::::::::::/:::::|
|¯¯\::::/\:/¯\::::/¯¯¯¯<::::/\::/¯¯\:/¯¯¯¯¯¯\::\::/¯¯\::::/¯¯\::::/¯¯¯¯<::::/¯|
|__ |¯¯|  T _ |¯¯¯| ___ |¯¯|  |¯| _ T ______ |¯¯¯¯| _ |¯¯¯| _ |¯¯¯| ___ |¯¯| _|
   \|__|/\|/ \|___|/   \|__|/\|_|/ \|/      \|    |/ \|___|/ \|___|/dNo\|__|/  

¬°¤*,¸¸,*¤°¬¯¬°¤*,¸_¸,*¤°¬°¤*,¸,*¤°¬¯¬°¤*,¸_¸,*¤°¬°¤*,¸,*¤°¬¯¬°¤*,¸_¸,*¤°¬°¤*,¸
¸,*¤°¬¯¬°¤*,¸_¸,*¤°¬°¤*,¸,*¤°¬¯¬°¤*,¸_¸,*¤°¬°¤*,¸,*¤°¬¯¬°¤*,¸_¸,*¤°¬°¤*,¸,*¤°¬¯

  This file is part of Etripator,
  copyright (c) 2009--2026 Vincent Cruz.
 
  Etripator is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
 
  Etripator is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
 
  You should have received a copy of the GNU General Public License
  along with Etripator.  If not, see <http://www.gnu.org/licenses/>.

¬°¤*,¸¸,*¤°¬¯¬°¤*,¸_¸,*¤°¬°¤*,¸,*¤°¬¯¬°¤*,¸_¸,*¤°¬°¤*,¸,*¤°¬¯¬°¤*,¸_¸,*¤°¬°¤*,¸
¸,*¤°¬¯¬°¤*,¸_¸,*¤°¬°¤*,¸,*¤°¬¯¬°¤*,¸_¸,*¤°¬°¤*,¸,*¤°¬¯¬°¤*,¸_¸,*¤°¬°¤*,¸,*¤°¬¯
*/
#include "wla_dx.h"

#include "message.h"
#include "output.h"

#include <assert.h>

bool wla_dx_output(MemoryMap *map, LabelRepository* labels, SectionArray *sections, const char* filename) {
    assert(sections != NULL);
    assert(labels != NULL);
    assert(filename != NULL);

    bool ret = false;

    FILE *out = fopen(filename, "w");
    if(out == NULL) {
        ERROR_MSG("Failed to open %s: %s", filename, strerror(errno));
    } else {
        fprintf(out, "; generated by Etripator\n");
        fprintf(out, "[information]\nversion 1\n");

        const char** filenames = calloc(sections->count, sizeof(char*));
        size_t n = 1;
        filenames[0] = sections->data[0].output;
        for(size_t i=1; i<sections->count; i++) {
            size_t j;
            for(j=0; (j<n) && strcmp(filenames[j], sections->data[i].output); j++) {
            }
            if(j>=n) {
                filenames[n] = sections->data[i].output;
                n++;
            }
        }

        fprintf(out, "\n[definitions]\n");
        for(size_t i=0; i<labels->last; i++) {
            const Label *current = &labels->labels[i];
            if(map->page[current->page].id != PCE_MEMORY_ROM) {
                uint32_t addr = current->logical;                       // [todo] ((current->page) << 13) | (current->logical & 0x1FFFU) ?
                fprintf(out, "%8.8x %s\n", addr, current->name);
            }
        }

        fprintf(out, "\n[symbols]\n");
        for(size_t i=0; i<labels->last; i++) {
            const Label *current = &labels->labels[i];
            if(map->page[current->page].id == PCE_MEMORY_ROM) {
                fprintf(out, "%2.2x", current->page);
                fprintf(out, ":%4.4x", current->logical);
                fprintf(out, " %8.8x", 0xC0000000UL);
                fprintf(out, " %4.4x:%8.8x:%2.2x", current->file_id, current->line, current->column);
                fprintf(out, " %s\n", current->name);
            }
        }


        fprintf(out, "\n[source-files]\n");
        for(size_t i=0; i<n; i++) {
            fprintf(out, "%4.4x \"%s\"", i, filenames[i]);
        }
        free(filenames);

        fprintf(out, "\n[bank-to-source]\n");
        // [todo]

        fclose(out);
    }
    return ret;
}
