name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: 'recursive'

    - name: Setup Dependencies
      run: |
        sudo apt install -y -qq libjansson-dev

    - name: Configure
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -Bbuild -S . -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: cmake --build ./build --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}
      shell: bash
      run: cmake --build ./build --target test
