name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
    - uses: actions/checkout@v7
      with:
          submodules: 'recursive'

    - name: Setup Dependencies
      run: |
        sudo apt install -y -qq libjansson-dev

    - name: Configure
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -Bbuild -S . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS:BOOL=TRUE

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: cmake --build ./build --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}
      shell: bash
      run: ctest --test-dir ./build --output-on-failure
